version: 2 
jobs: 
  build: 
    docker: 
      - image: circleci/golang:1.8 
    working_directory: /go/src/github.com/integr8ly/managed-service-broker

    steps:
      - checkout 
      - run: make build_binary
    
  docker_push:
    docker:
      # Node 10 LTS
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run: ./scripts/docker_build_and_push.sh

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - docker_push:
      requires: 
        - build
