version: 2 
jobs: 
  build: 
    docker: 
      - image: circleci/golang:1.8 
    working_directory: /go/src/github.com/integr8ly/managed-service-broker

    steps:
      - checkout 
      - run: make build_binary
    
    docker_push:
      - run: "./scripts/docker_push.sh"
