apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managedservicenamespaces.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: ManagedServiceNamespace
    listKind: ManagedServiceNamespaceList
    plural: managedservicenamespaces
    singular: managedservicenamespace
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            managedNamespace:
              type: string
            consumerNamespaces:
              type: array